# Generated by Django 4.0.6 on 2022-07-09 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorumodeli',
            options={'verbose_name': 'Soru Modeli', 'verbose_name_plural': 'Soru Modeli'},
        ),
        migrations.AddField(
            model_name='sorumodeli',
            name='düzenlenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sorumodeli',
            name='icerik',
            field=models.TextField(default='icerik yaz'),
        ),
        migrations.AddField(
            model_name='sorumodeli',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
