# Generated by Django 4.0.6 on 2022-07-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_sorumodeli_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorumodeli',
            name='resim',
            field=models.ImageField(default='selamdunya', upload_to='yazi_resimleri'),
        ),
    ]
