# Generated by Django 4.0.6 on 2022-07-09 11:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sorumodeli_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorumodeli',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
