# Generated by Django 4.0.6 on 2022-07-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_yorummodeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanaUlasModeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('isim_soyisim', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'iletisim',
            },
        ),
    ]
