# Generated by Django 4.0.6 on 2022-07-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_banaulasmodeli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banaulasmodeli',
            options={'verbose_name': 'Bana Ulas', 'verbose_name_plural': 'Ulasma'},
        ),
    ]
