# Generated by Django 4.0.6 on 2022-07-10 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_banaulasmodeli_mesaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjelerimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('icerik', ckeditor.fields.RichTextField()),
                ('resim', models.ImageField(default='selamdunya', upload_to='yazi_resimleri')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('düzenlenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
