# Generated by Django 4.0.6 on 2022-07-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_projelerimmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projelerimmodel',
            options={'verbose_name': 'Bana Proje', 'verbose_name_plural': 'Projema'},
        ),
        migrations.AlterModelTable(
            name='projelerimmodel',
            table='Projelerim',
        ),
    ]
