# Generated by Django 4.0.6 on 2022-07-11 18:57

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_projelerimmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorumodeli',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
