# Generated by Django 4.0.6 on 2022-07-11 19:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_sorumodeli_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorumodeli',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='isim', unique=True),
        ),
    ]
